name: CI

on:
  push: {}
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - rockylinux:8
#          - debian:buster
#          - debian:bullseye
#          - debian:sid
          - fedora:29
          - fedora:30
          - fedora:31
          - fedora:32
          - fedora:33
          - fedora:34
          - fedora:35
          - fedora:36
          - fedora:37
#          - ubuntu:20.04
#          - ubuntu:21.10
#          - ubuntu:22.04
#          - opensuse/leap:15.3
#          - opensuse/leap:15.4
#          - mageia:7
          - mageia:8
    container:
      image: ${{ matrix.container }}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: "test.sh"
        run: |
          ./test.sh ${{ matrix.container }}
