name: CI

on:
  push: {}
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - rockylinux:8.5
          - rockylinux:8.6
          - rockylinux:9
          - fedora:29
          - fedora:30
          - fedora:31
          - fedora:32
          - fedora:33
          - fedora:34
          - fedora:35
          - fedora:36
          - fedora:37
          - mageia:8
    container:
      image: ${{ matrix.container }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: "test.sh"
        run: |
          ./test.sh ${{ matrix.container }}
